version: "3"
services:
  webserver:
    image: nginx:1.11
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/sites-enabled/default.conf.template:/tmp/default.conf.template
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./shared/htdocs:/var/www/html:ro
    depends_on:
      - php
    networks:
      - front
      - back
    command: /bin/bash -c "if [ ! -d /etc/nginx/sites-enabled/ ]; then mkdir /etc/nginx/sites-enabled/; fi && sed 's/###NGINX_SERVER_NAME###/${DOMAIN}/' /tmp/default.conf.template > /etc/nginx/sites-enabled/default.conf && nginx -g 'daemon off;'"

  php:
    build: config/php
    args:
      - user_id=${USER_ID}
    user: www-data
    volumes:
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./shared/htdocs:/var/www/html
    environment:
      COMPOSER_HOME: /tmp
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
    depends_on:
      - mysql
    networks:
      - back

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./shared/db:/var/lib/mysql
    networks:
      - back

networks:
  front:
    driver: bridge
  back:
    driver: bridge
